### ISSUE TITLE
Observations:  Response to DISC frames.  Multiple responses to I frames.

### ISSUE THREAD

**Issue by VK2FAB** [dotb/pakcatt#1]
I make the following observations against the VK3AT system (the only system I have ready access to test against):

 If I send a 'DISC' frame to any address on the network, the system seems to respond to that frame assuming the address of the address I am targeting with the disconnect frame.  For example, were I to send a disconnect frame to address [TEST], the system would respond with a 'UA' frame sourced from the address [TEST].  This could be an issue with regulatory compliance and perhaps also lead to some kind of denial of service for other users on the network.

**Comment by dotb** [comment]
Thanks @VK2FAB!

Hope you don't mind, I've separated this into two issues. The second is here:
https://github.com/dotb/pakcatt/issues/2

**Comment by dotb** [comment]
I've added a fix: https://github.com/dotb/pakcatt/commit/3a1883845e9bfcf8f1d64d0126d320b2bfd719e9
and deployed to VK3AT-1. If you have a minute, please test again and let me know if notice anything out of order @VK2FAB @jeauxlb.
Thanks again @VK2FAB
